apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: SPRING_DATASOURCE_URL